### PR TITLE
Support Serial dates parsing

### PR DESCRIPTION
**Pull request by dbernheisel**
This was https://github.com/taxjar/date_time_parser/pull/2 but with the refactoring pulled out of the PR.

Add support for serial datetime parsing (found in common spreadsheet programs).

I was looking at https://github.com/jsonkenl/xlsxir/blob/master/lib/xlsxir/convert_datetime.ex and noticed it was not that terrible to parse spreadsheet serial timestamps, so I thought I'd add support here too.
New Serial parser. This one doesn't actually use NimbleParsec. Instead it's a float that gets transformed into a NaiveDateTime through some math.

### CODE REVIEW

**Comment by dbernheisel** [comment]
Updated to consider if the string is an integer or a float.

- If it's a float, then we have some positive indication that there is time, so return a `%NaiveDateTime{}`
- If it's an integer, then we don't know if time can be assumed, so only return a `%Date{}`

**Comment by cas27** [comment]
I wonder if a case could be made to force any integer to be treated as either epoch or serial?

**Comment by dbernheisel** [comment]
@cas27 I would want `20190429` to parse as 2019-04-29 though, and not be treated as a serial date or epoch.

Here's how we currently do it (in this PR)

|digits|parser|range|
|---|----|---|
|1-5|Serial|low = 1900-01-01, high = 2173-10-15|
|6-9|treated as regular datetime string (allowing for 20190429 to be parsed)|any|
|1-11 (right now restricted to 10-11 digits)|Epoch|low = 1976-03-03T09:46:40, high = 5138-11-16 09:46:39|

It's ambiguous between serial and epoch timestamps, but trying to pick the most likely one based on number of digits.

Since we're currently restricting epoch to 10-11 digits, we have a span of epochs that are not parsed correctly: 1970-01-01T12:00:00 through 1976-03-03T09:46:39

**Comment by cas27** [comment]
Sounds reasonable!

**Pull request merged**
