### PR TITLE
Account for 4-digit year in US-formatted date

### LINKED ISSUE #27: "2010/01/01" parsed incorrectly
```elixir
iex(1)> DateTimeParser.parse("2010/01/01")
{:ok, ~D[0201-10-20]}
```

should be `~D[2010-01-01]` but looks like it's fooled by the slash.

### PR DESCRIPTION
**Pull request by dbernheisel**
Resolves #27 

This adds a branch to check for year4-month-day using the US-date parser.

### CODE REVIEW

**Comment by cas27** [comment]
Looks good.  Whats your thoughts about backsplashes instead of forward?

`iex(10)> DateTimeParser.parse "2020\01\19"     
{:ok, ~T[20:20:00]}
iex(11)> DateTimeParser.parse_date "2020\01\19"
{:error,
 <<67, 111, 117, 108, 100, 32, 110, 111, 116, 32, 112, 97, 114, 115, 101, 32,
   50, 48, 50, 48, 0, 49, 49, 57>>}
iex(12)> DateTimeParser.parse_date "2010\01\19"
{:error,
 <<67, 111, 117, 108, 100, 32, 110, 111, 116, 32, 112, 97, 114, 115, 101, 32,
   50, 48, 49, 48, 0, 49, 49, 57>>}`

**Comment by dbernheisel** [comment]
I've not seen dates with that slash, but not opposed to adding support for it in another PR

**Comment by dbernheisel** [comment]
Btw is that the error message you got? The binary stuff? If so I'll definitely want to fix that.

**Comment by cas27** [comment]
> Btw is that the error message you got? The binary stuff? If so I'll definitely want to fix that.

It is

**Comment by cas27** [comment]
> I've not seen dates with that slash, but not opposed to adding support for it in another PR

Sounds good.

**Comment by dbernheisel** [comment]
That "2020\01\01" is returning with an error in binary because (I think) Elixir is interpreting "\0" as an escaped 0.

```elixir
iex(34)> "\0"
<<0>>
```

which makes the error unprintable since it gives you back the string it received. In this case, to avoid the `\0` being interpreted, it can be provided with the `~S` sigil, eg, `DateTimeParser.parse_date(~S(2020\01\01))`

**Pull request merged**
